#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipaddr
Version  : 2.1.11
Release  : 14
URL      : https://pypi.python.org/packages/source/i/ipaddr/ipaddr-2.1.11.tar.gz
Source0  : https://pypi.python.org/packages/source/i/ipaddr/ipaddr-2.1.11.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : Apache-2.0
Requires: ipaddr-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
ipaddr.py is a library for working with IP addresses, both IPv4 and IPv6.
It was developed by Google for internal use, and is now open source.

%package python
Summary: python components for the ipaddr package.
Group: Default

%description python
python components for the ipaddr package.


%prep
%setup -q -n ipaddr-2.1.11

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python ipaddr_test.py
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
