#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipaddr
Version  : 2.2.0
Release  : 27
URL      : http://pypi.debian.net/ipaddr/ipaddr-2.2.0.tar.gz
Source0  : http://pypi.debian.net/ipaddr/ipaddr-2.2.0.tar.gz
Summary  : Google's IP address manipulation library
Group    : Development/Tools
License  : Apache-2.0
Requires: ipaddr-python3
Requires: ipaddr-python
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
It has been superseded by ipaddress from the Python 3 standard library, and its
        Python 2 backport.

%package python
Summary: python components for the ipaddr package.
Group: Default
Requires: ipaddr-python3

%description python
python components for the ipaddr package.


%package python3
Summary: python3 components for the ipaddr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ipaddr package.


%prep
%setup -q -n ipaddr-2.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523289890
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python ipaddr_test.py
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
